name = 'My Game'

modules = [
    './main',
    '@rpgjs/mobile-gui',
    '@rpgjs/default-gui',
    '@rpgjs/plugin-emotion-bubbles',
    '@rpgjs/gamepad'
]

[inputs.builder-dashboard]
    name = "builder-dashboard"
    bind = "b"

[inputs.conversation-log]
    name = "conversation-log"
    bind = "l"

[start]
    map = 'simplemap'
    graphic = 'hero'
    hitbox = [16, 16]